services:
  adf:
    image: ontotext/adf:1.8.0
    restart: unless-stopped
    environment:
      KEYCLOAK_URL: "${POOLPARTY_KEYCLOAK_AUTHURL}"
      KEYCLOAK_REALM: "${POOLPARTY_KEYCLOAK_LOGIN_REALM}"
      POOLPARTY_URL: "${SERVER_URL}"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_PPT_CLIENTSECRET: "${POOLPARTY_KEYCLOAK_LOGIN_CLIENTSECRET}"
      MANAGEMENT_ENDPOINTS_WEB_CORS_ALLOWED_ORIGINS: "${SERVER_URL}"
    extra_hosts:
      - "${SERVER_NAME}:host-gateway"
    volumes:
      - adf_data:/var/lib/adf

  semantic-workbench:
    image: ontotext/semantic-workbench:2.4.0
    restart: unless-stopped
    environment:
      KEYCLOAK_URL: "${POOLPARTY_KEYCLOAK_AUTHURL}"
      KEYCLOAK_REALM: "${POOLPARTY_KEYCLOAK_LOGIN_REALM}"
      POOLPARTY_URL: "${SERVER_URL}"
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_PPT_CLIENTSECRET: "${POOLPARTY_KEYCLOAK_LOGIN_CLIENTSECRET}"
      POOLPARTY_LICENSE_PATH: "/usr/share/semantic-workbench"
      MANAGEMENT_ENDPOINTS_WEB_CORS_ALLOWED_ORIGINS: "${SERVER_URL}"
      # todo: the app version should not be explicitly configured
      APPLICATION_VERSION: "2.4.0"
    extra_hosts:
      - "${SERVER_NAME}:host-gateway"
    volumes:
      - "${POOLPARTY_LICENSE}:/usr/share/semantic-workbench/poolparty.key"
      - semantic-workbench_data:/var/lib/semantic-workbench

  graphviews:
    image: ontotext/graphviews:1.0.0
    restart: unless-stopped
    environment:
      PP_USERNAME: superadmin
      PP_PASSWORD: ${POOLPARTY_SUPER_ADMIN_PASSWORD}
      PP_URL: "${SERVER_URL}"
    extra_hosts:
      - "${SERVER_NAME}:host-gateway"

  mirror-app:
    image: ontotext/mirror-app:2.4.1
    restart: unless-stopped
    ports:
      - "8008:8008"
    #environment:
    #  MIRROR_CONFIG: /app/server-map.json
    #volumes:
    #  - /path/to/external/server-map.json:/app/server-map.json

volumes:
  adf_data:
  semantic-workbench_data:
